data_dir: "../../../data/fastq_combined_GSIDs"
results_dir: "../../../results/combinedGSIDs"
mixcr_species: "hsa"
mixcr_preset: "takara-human-rna-tcr-umi-smartseq"
read_thresholds: [1]
# New parameter for Java heap memory
mixcr_memory: "500g"
